# -*- coding: utf-8 -*-
"""Write the current data state into both READMEs, so it cannot go stale again.

It went stale twice, and the second time it was not merely out of date but wrong: the
xLadder README claimed the NRL ran through round 17 and Super League through round 16,
when the masters held 20 and 19. A reader checking whether the data covered a fixture
would have got the wrong answer from the document whose job is to say.

The fix is not to be more careful. It is to generate the paragraph. Everything between
the two markers is replaced on each run and nothing outside them is touched, so the prose
around it stays hand-written.

    python datastate.py            # rewrite both READMEs
    python datastate.py --check    # exit 1 if either is out of date, printing the diff
"""
import argparse
import io
import os
import sqlite3
import sys

import pandas as pd

BASE = os.path.dirname(os.path.abspath(__file__))
DB = os.path.join(BASE, "tallec.db")
AUDIT = os.path.join(BASE, "tallec_audit.db")
# Two layouts: the deploy repo, where this folder is NRL_2026_MPT/tallec and the xLadder
# masters are one level up, and the standalone TALLEC working copy beside NRL_2026_MPT.
# The parent counts as the xLadder repo only if its pipeline is there too: a stray master
# in a parent folder was silently picked up once before (see team_map.py).
_UP = os.path.abspath(os.path.join(BASE, ".."))
XLADDER = (_UP if all(os.path.exists(os.path.join(_UP, f))
                      for f in ("xladder_pipeline.py", "NRL_master.xlsx"))
           else os.path.join(_UP, "NRL_2026_MPT"))

BEGIN = "<!-- DATA-STATE:BEGIN — generated by datastate.py, do not edit by hand -->"
END = "<!-- DATA-STATE:END -->"
COMP_NAME = {"NRL": "NRL", "SL": "Super League", "NSW": "NSW Cup",
             "QLD": "Queensland Cup"}


def _table(rows, cols):
    out = ["| " + " | ".join(cols) + " |", "| " + " | ".join("---" for _ in cols) + " |"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def tallec_block():
    con = sqlite3.connect(DB)
    d = pd.read_sql("SELECT competition, season, COUNT(*) n, "
                    "COUNT(DISTINCT round) rounds, COUNT(DISTINCT player_id) players "
                    "FROM player_match_stats GROUP BY 1,2", con)
    ratings = pd.read_sql("SELECT competition, season, COUNT(*) n FROM player_ratings "
                          "GROUP BY 1,2", con)
    try:
        pos = pd.read_sql("SELECT COUNT(*) n FROM player_position_metrics", con).n.iloc[0]
    except Exception:
        pos = 0
    con.close()
    try:
        a = sqlite3.connect(AUDIT)
        last = pd.read_sql("SELECT target, MAX(run_at) at FROM model_runs GROUP BY 1", a)
        a.close()
    except Exception:
        last = pd.DataFrame()

    rows = []
    for comp, g in d.groupby("competition"):
        rows.append([COMP_NAME.get(comp, comp),
                     f"{int(g.season.min())}–{int(g.season.max())}",
                     f"{int(g.n.sum()):,}",
                     f"{int(g[g.season == g.season.max()].rounds.iloc[0])}",
                     f"{int(g.players.max())}"])
    out = [BEGIN, "",
           f"`tallec.db` holds **{int(d.n.sum()):,} player-match rows** across "
           f"{d.competition.nunique()} competitions and {len(d)} league-seasons.", "",
           _table(rows, ["Competition", "Seasons", "Player-matches",
                         "Rounds in latest", "Players in a season"]), ""]
    if len(ratings):
        s = ", ".join(f"{COMP_NAME.get(r.competition, r.competition)} "
                      f"{int(r.season)} ({int(r.n)})"
                      for r in ratings.itertuples())
        out.append(f"Ratings are published for: {s}. "
                   f"Position metrics hold {int(pos):,} figures.")
        out.append("")
    if len(last):
        out.append("Last rebuilt: "
                   + "; ".join(f"`{r.target}` {r.at[:10]}" for r in last.itertuples())
                   + ".")
        out.append("")
    out.append(END)
    return "\n".join(out)


def xladder_block():
    rows = []
    note = []
    for lg, f in (("NRL", "NRL_master.xlsx"), ("SL", "SL_master.xlsx")):
        p = os.path.join(XLADDER, f)
        if not os.path.exists(p):
            note.append(f"`{f}` not found at {XLADDER}.")
            continue
        m = pd.read_excel(p, usecols=["Season", "Round", "A_Points Scored",
                                      "B_Points Scored"])
        for season, g in m.groupby("Season"):
            played = g["A_Points Scored"].notna()
            rows.append([COMP_NAME[lg], int(season), len(g), int(played.sum()),
                         int(g.Round.max()),
                         f"{(g['A_Points Scored'] - g['B_Points Scored']).abs().mean():.1f}"])
    out = [BEGIN, "",
           "One row per match. The mean absolute margin is the sanity check that "
           "matters: a season far below the others has misaligned rows, which is how "
           "the Super League 2025 corruption was caught — it read 7.0 where every other "
           "season reads 15 to 19.", "",
           _table(rows, ["Competition", "Season", "Fixtures", "Played", "Last round",
                         "Mean margin"]), ""]
    out += note + [END]
    return "\n".join(out)


def apply(path, block, anchor):
    """Replace the marked region, or insert it under `anchor` the first time."""
    if not os.path.exists(path):
        return None, f"{path} not found"
    s = io.open(path, encoding="utf-8").read()
    if BEGIN in s and END in s:
        new = s[:s.index(BEGIN)] + block + s[s.index(END) + len(END):]
    elif anchor in s:
        i = s.index(anchor) + len(anchor)
        j = s.index("\n", i) + 1
        new = s[:j] + "\n" + block + "\n" + s[j:]
    else:
        new = s.rstrip() + "\n\n## Data state\n\n" + block + "\n"
    return new, None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report whether either README is out of date, write nothing")
    a = ap.parse_args()

    targets = [(os.path.join(BASE, "README.md"), tallec_block(),
                "## What is in the database"),
               (os.path.join(XLADDER, "README.md"), xladder_block(), "## Data state")]
    stale = 0
    for path, block, anchor in targets:
        new, err = apply(path, block, anchor)
        if err:
            print(f"  {err}")
            continue
        old = io.open(path, encoding="utf-8").read()
        name = os.path.relpath(path, BASE)
        if new == old:
            print(f"  {name}: already current")
            continue
        stale += 1
        if a.check:
            print(f"  {name}: OUT OF DATE")
        else:
            io.open(path, "w", encoding="utf-8", newline="\n").write(new)
            print(f"  {name}: updated")
    if a.check and stale:
        print("\nRun `python datastate.py` to bring them up to date.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
